name: eftpipe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - getdist>=1.3.1
  # getdist dependencies
  - numpy>=1.20
  - scipy>=1.6
  - pandas>=1.0.1
  - matplotlib
  - PyYAML>=5.1
  - PySide2
  # cobaya dependencies
  - portalocker>=2.3.0
  - tqdm
  - fuzzywuzzy>=0.17
  - requests>=2.18
  - urllib3>=1.22
  - dill>=0.3.3
  - packaging
  # cosmo
  - camb>=1.3.5
  # miscellaneous
  - numba
  - cython<3.0
  - pip
  - pip:
    - cobaya>=3.2.1
    - -e . # editable install of eftpipe