name: eftpipe-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - typing_extensions>=4.1,<5.0
  # getdist dependencies
  - numpy>=1.20
  - scipy>=1.6
  - pandas>=1.0.1
  - matplotlib
  - PyYAML>=5.1
  - PySide2
  # end
  # cobaya dependencies
  - portalocker>=2.3.0
  - tqdm
  - fuzzywuzzy>=0.17
  - requests>=2.18
  - urllib3>=1.22
  - dill>=0.3.3
  - packaging
  # end
  # test framework
  - pytest>=6.0
  - pytest-cov
  - pytest-regressions>=2.3.0
  - pytest-datadir
  # end
  # miscellaneous
  - ipython
  - line_profiler
  - numba
  # end
  - pip
  - pip:
    # pypi mirrors
    # - --index-url https://
    # - --extra-index-url https://
    # end
    - getdist>=1.3.1
    - cobaya>=3.2.1,<3.3
    - -e . # editable install of eftpipe