[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
addopts = "-ra --color=yes"
markers = [
    "diffbird: mark test to enable comparison to pybird_dev",
    "fcompare: show failed comparison",
]
# for future coverage test
# addopts = "-ra --cov --cov-report=xml --cov-config=.coveragerc --color=yes"